(function () {
  'use strict';
  var app=document.getElementById('app'), nav=document.querySelectorAll('.nav');
  var VERSION='20260929-65';
  var BASE='https://skuoxmrzlxhebzhfgbyn.supabase.co';
  var KEY='sb_publishable_u46tZ4GMUgwqSYhMJNFG8Q_IzYwl95T';
  var CLIENT='ecommerce-agent-sandbox-v1';
  var state={view:location.hash.slice(1)||'overview',run:null,game:[],market:[],ads:{},backtests:[],events:[],memories:[],risk:[],tasks:[],agentRounds:[],simulation:{status:'idle',message:''}};
  var adTables=['sandbox_ad_plans','sandbox_ad_units','sandbox_ad_keywords','sandbox_ad_keyword_moves','sandbox_ad_audiences','sandbox_ad_audience_combos','sandbox_ad_creatives','sandbox_ad_placements','sandbox_ad_regions','sandbox_ad_timeslots','sandbox_ad_negative_keywords','sandbox_ad_agent_actions','sandbox_ad_results','sandbox_ad_reports'];
  function zh(v){var m={'HOLD':'保持观察','CHANGE_KEYWORD':'调整关键词','CHANGE_TARGETING':'调整定向','CHANGE_CONTENT':'调整内容','CHANGE_AUDIENCE':'调整人群','CHANGE_CREATIVE':'调整创意','CHANGE_PRICE':'调整价格','INCREASE_BUDGET':'增加预算','DECREASE_BUDGET':'降低预算','INCREASE_BID':'提高出价','DECREASE_BID':'降低出价','DEFEND_TRAFFIC':'防守流量','SHIFT_CONTENT':'切换内容','VALUE_ATTACK':'价值竞争','NO_CLEAR_GAP':'暂未发现明确突破口','ALLOW':'通过','BLOCK':'拦截','STOP':'停止','CONTINUE':'继续','POSITIVE':'正向','NEGATIVE':'负向','INCONCLUSIVE':'结果不明确','OBSERVE':'观察','DEFENSIVE':'防守','MIXED':'混合','UNKNOWN':'未知','ANALYZE_ONLY':'仅分析','AUTO':'自动选择','OUR_AGENT':'我方智能体','OPP-01':'价格竞争方','OPP-02':'流量竞争方','OPP-03':'内容竞争方','CATARGETING':'定向投放','CA_TARGETING':'定向投放','TARGETING':'定向投放','targeting':'定向投放','catargeting':'定向投放'};return m[v]||v||'';}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function show(title,sub,body){app.innerHTML='<h1 class="page-title">'+esc(title)+' <span style="font-size:16px;font-weight:500;color:var(--accent);margin-left:10px">我变 → 对手学 → 我再变</span></h1><div class="subtitle">'+esc(sub)+'</div><div class="card" style="margin:10px 0 16px;border-left:4px solid var(--accent);background:rgba(255,180,0,.06)"><b>连续博弈座右铭</b><div style="font-size:18px;margin-top:6px">我变 → 对手学 → 我再变</div></div>'+body;}
  function notice(v){return '<div class="card"><div class="notice">'+esc(v)+'</div></div>';}
  function table(h,rows){if(!rows.length)return notice('暂无记录');var s='<div class="card"><table class="table"><thead><tr>'+h.map(esc).map(function(x){return'<th>'+x+'</th>';}).join('')+'</tr></thead><tbody>';rows.forEach(function(r){s+='<tr>'+r.map(esc).map(function(x){return'<td>'+x+'</td>';}).join('')+'</tr>';});return s+'</tbody></table></div>';}
  function getJSON(url,options){return fetch(url,Object.assign({headers:{apikey:KEY,Authorization:'Bearer '+KEY,Accept:'application/json'},cache:'no-store'},options||{})).then(function(res){return res.text().then(function(t){var d={};try{d=JSON.parse(t);}catch(e){throw new Error('HTTP '+res.status+' 返回非 JSON');}if(!res.ok)throw new Error('HTTP '+res.status);return d;});});}
  function runURL(name,scoped){var q='?select=*&order=id.desc';if(scoped&&state.run&&state.run.id)q+='&run_id=eq.'+encodeURIComponent(state.run.id);return BASE+'/rest/v1/'+name+q;}
  function loadRun(){return getJSON(BASE+'/rest/v1/sandbox_runs?select=id,status,updated_at,client_key,agent_progress,backtest_progress,risk_progress,memory_count,run_count,state&client_key=eq.'+encodeURIComponent(CLIENT)+'&order=updated_at.desc&limit=1').then(function(r){if(!r.length)throw new Error('没有找到 sandbox_runs');state.run=r[0];});}
  function loadCore(){return Promise.all([getJSON(runURL('sandbox_game_states',true)),getJSON(runURL('sandbox_market_signals',true)),getJSON(runURL('sandbox_backtests',true)),getJSON(runURL('sandbox_events',true)),getJSON(runURL('sandbox_memories',true)),getJSON(runURL('sandbox_risk_results',true)),getJSON(runURL('sandbox_task_results',true)),getJSON(runURL('sandbox_agent_rounds',true))]).then(function(x){state.game=x[0]||[];state.market=x[1]||[];state.backtests=x[2]||[];state.events=x[3]||[];state.memories=x[4]||[];state.risk=x[5]||[];state.tasks=x[6]||[];state.agentRounds=x[7]||[];var s=state.run&&state.run.state||{};if(!state.agentRounds.length&&Array.isArray(s.executedPath))state.agentRounds=s.executedPath.map(function(p,i){return{round:p.round||i+1,action:p.action||'HOLD',actual_opponent_response:p.response||p.actual_opponent_response||'暂无',next_action_hint:p.nextAction||p.next_action_hint||'HOLD',breakthrough:p.breakthrough||'',roi:p.roi,marginal_roi:p.marginal_roi,risk_approved:p.risk_approved!==false,stop_signal:!!p.stop_signal,stop_reason:p.stop_reason||''};});if(!state.game.length&&Array.isArray(s.game))state.game=s.game;if(!state.market.length&&Array.isArray(s.market))state.market=s.market;if(!state.market.length&&Array.isArray(s.marketSignals))state.market=s.marketSignals;});}
  function loadAds(){return Promise.all(adTables.map(function(n){return getJSON(runURL(n)).then(function(r){state.ads[n]=r||[];});}));}
  function overview(){var rounds=state.agentRounds||[];var last=rounds.length?rounds[rounds.length-1]:null;var chain='<div class="card"><div class="label">连续博弈动态链</div><div style="display:flex;gap:8px;overflow:auto;padding:12px 0">';[['01','输入','我方 + 对手 + 市场'],['02','突破口','识别竞争结构'],['03','策略','选择本轮动作'],['04','风险控制','资金 / 市场 / 对手风险'],['05','执行','模拟价格、投流、内容'],['06','对手响应','记录实际反应'],['07','市场反馈','ROI / 转化 / 拥挤'],['08','学习','进入下一轮']].forEach(function(x){chain+='<div style="min-width:150px;border:1px solid var(--line);border-radius:10px;padding:10px"><span class="tag">'+x[0]+'</span><br><b>'+x[1]+'</b><div class="muted">'+x[2]+'</div></div>';});chain+='</div>'+(last?'<div class="notice">当前：R'+esc(last.round)+' · '+zh(last.action)+' → '+zh(last.actual_opponent_response)+' → '+zh(last.next_action_hint)+'</div>':'<div class="notice">当前 Sandbox 尚无可播放轮次。</div>')+'</div>';
    var rows=rounds.map(function(r){return['R'+(r.round||''),zh(r.action),zh(r.actual_opponent_response),zh(r.next_action_hint),r.roi==null?'-':r.roi,r.risk_approved===false?'拦截':'通过'];});
    var playback='<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap"><div><div class="label">Agent Sandbox 多轮模拟</div><div class="metric">'+(rounds.length?('已读取 '+rounds.length+' 轮'):'暂无模拟轮次')+'</div></div><div><button class="action" id="sim-start">▶ 开始10轮模拟</button><button class="action" id="sim-refresh">↻ 读取最新模拟</button></div></div>'+(rows.length?table(['轮次','我方动作','实际对手响应','下一动作','ROI','风险'],rows):'<div class="notice">数据库当前没有 Agent 轮次；如果刚完成模拟，请点击“读取最新模拟”。</div>')+'</div>';
    show('商业博弈总览','Sandbox Run · '+(state.run?state.run.status:'未知'),'<div class="grid"><div class="card"><div class="label">Sandbox Run</div><div class="metric">'+esc(state.run?state.run.status:'unknown')+'</div></div><div class="card"><div class="label">商业博弈记录</div><div class="metric">'+state.game.length+'</div></div><div class="card"><div class="label">市场信号</div><div class="metric">'+state.market.length+'</div></div><div class="card"><div class="label">Agent闭环轮次</div><div class="metric">'+rounds.length+'</div></div></div>'+chain+playback);bindSimulationButtons();}
  function bindSimulationButtons(){var a=document.getElementById('sim-start'),b=document.getElementById('sim-refresh');if(a)a.onclick=startSimulation;if(b)b.onclick=function(){loadRun().then(loadCore).then(loadAds).then(render).catch(function(e){alert('读取失败：'+e.message);});};}
  function startSimulation(){var ctx={client_key:CLIENT,rounds:10,strategy_context:{type:'AUTO',id:'',name:'自动选择',action:'',signal:'',goal:''}};var a=document.getElementById('sim-start');if(a){a.disabled=true;a.textContent='正在运行…';}getJSON(BASE+'/functions/v1/sandbox-agent-runner',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'},body:JSON.stringify(ctx)}).then(function(){return loadRun().then(loadCore).then(loadAds);}).then(render).catch(function(e){alert('启动模拟失败：'+e.message);render();});}
  function market(){show('外部市场情报','Sandbox 市场信号',table(['名称','类型','强度','说明'],state.market.map(function(x){return[x.name,x.signal_type,x.strength,x.detail];})));}
  function gameLogic(){var list=window.EA_GAME_LOGICS||[];var h='<div class="card"><div class="label">博弈逻辑库</div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:8px">';list.forEach(function(x){h+='<div class="notice"><b>'+esc(x.id)+' '+esc(x.name)+'</b><br><span class="muted">'+esc(x.type||'')+'</span></div>';});h+='</div></div>';show('博弈逻辑','50套博弈逻辑与棋谱',h);}
  function generic(title,key){var list=window[key]||[];show(title,'策略库','<div class="card"><div class="label">'+list.length+'项</div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:8px">'+list.map(function(x){return'<div class="notice"><b>'+esc(x.id||'')+' '+esc(x.name||'')+'</b><br><span class="muted">'+esc(x.signal||x.style||x.category||'')+'</span></div>';}).join('')+'</div></div>');}
  function render(){nav.forEach(function(n){n.classList.toggle('active',n.dataset.view===state.view);});try{if(state.view==='overview')overview();else if(state.view==='market')market();else if(state.view==='game-logic')gameLogic();else if(state.view==='positive-attacks')generic('正向攻击','EA_POSITIVE_ATTACK_LIBRARY');else if(state.view==='threats')threats();else if(state.view==='human-behavior')generic('人性行为演变','EA_HUMAN_BEHAVIOR_LIBRARY');else if(state.view==='strategy-center')generic('连续博弈策略中心','EA_HUMAN_BEHAVIOR_LIBRARY');else if(state.view==='ad-bidding-game')generic('广告投流博弈','EA_POSITIVE_ATTACK_LIBRARY');else if(state.view==='ads')show('广告流量','Sandbox 广告数据链','<div class="grid">'+adTables.map(function(n){return'<div class="card"><div class="label">'+esc(n.replace('sandbox_ad_',''))+'</div><div class="metric">'+(state.ads[n]||[]).length+'</div></div>';}).join('')+'</div>');else if(state.view==='experiments')show('实验与回测','Sandbox',table(['场景','轮次','ROI','风险','动作','时间'],state.backtests.map(function(x){return[x.scenario,x.rounds,x.roi,x.risk,x.action,x.created_at];})));else if(state.view==='risk')show('风险控制器','Sandbox',table(['指标','结果','时间'],state.risk.map(function(x){return[x.metric,JSON.stringify(x.value),x.created_at];})));else if(state.view==='jobs')show('任务监控','Sandbox Agent',table(['任务类型','状态','进度','时间'],state.tasks.map(function(x){return[x.task_type,x.status,x.progress+'%',x.created_at];}))+'<h2>事件流</h2>'+table(['事件类型','标题','详情','时间'],state.events.map(function(x){return[x.event_type,x.title,x.detail,x.created_at];})));else if(state.view==='memory')show('学习记忆','Sandbox',table(['记忆类型','内容','置信度','状态','时间'],state.memories.map(function(x){return[x.memory_type,x.content,x.confidence,x.status,x.created_at];})));}catch(e){show('当前模块加载失败','其他页面不受影响',notice(e.message));}}
  nav.forEach(function(n){n.addEventListener('click',function(){state.view=n.dataset.view;location.hash=state.view;render();});});
  window.__EA_APPDB_LOADED__=true;window.__EA_APPDB_VERSION__=VERSION;
  loadRun().then(loadCore).then(loadAds).then(render).catch(function(e){show('核心数据读取失败','请检查 Sandbox 数据连接',notice(e.message));});
}());