(function(){'use strict';
var app=document.getElementById('app'),nav=[].slice.call(document.querySelectorAll('.nav'));
var API='https://skuoxmrzlxhebzhfgbyn.supabase.co/functions/v1/sandbox-state',SUPA='https://skuoxmrzlxhebzhfgbyn.supabase.co',KEY='ecommerce-agent-sandbox-v1',ANON='sb_publishable_u46tZ4GMUgwqSYhMJNFG8Q_IzYwl95T';
var s={view:location.hash.slice(1)||'overview',run:null,db:{},loading:false,error:null};
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function page(t,sub,b){return'<h1 class="page-title">'+esc(t)+'</h1><div class="subtitle">'+esc(sub)+'</div>'+b}
function table(h,rs){if(!rs.length)return'<div class="card"><div class="notice">数据库当前没有该页面的数据。</div></div>';return'<div class="card"><table class="table"><thead><tr>'+h.map(function(x){return'<th>'+esc(x)+'</th>'}).join('')+'</tr></thead><tbody>'+rs.map(function(r){return'<tr>'+r.map(function(x){return'<td>'+esc(x)+'</td>'}).join('')+'</tr>'}).join('')}</tbody></table></div>'}
function getJSON(url,timeout){var ctl=new AbortController(),timer=setTimeout(function(){ctl.abort()},timeout||6000);return fetch(url,{headers:{apikey:ANON,Authorization:'Bearer '+ANON,Accept:'application/json'},mode:'cors',cache:'no-store',signal:ctl.signal}).then(function(r){return r.text().then(function(t){var j;try{j=JSON.parse(t)}catch(e){throw Error('HTTP '+r.status+' 返回非JSON：'+t.slice(0,160))}if(!r.ok)throw Error('HTTP '+r.status+'：'+(j.message||j.hint||j.error||t.slice(0,160)));return j})}).catch(function(e){if(e.name==='AbortError')throw Error('请求超过6秒未返回');throw e}).finally(function(){clearTimeout(timer)})}
function directRun(){return getJSON(SUPA+'/rest/v1/sandbox_runs?select=*&client_key=eq.'+encodeURIComponent(KEY)+'&order=updated_at.desc&limit=1',6000).then(function(rows){if(!rows||!rows.length)throw Error('数据库已连接，但没有找到当前 Sandbox run');return rows[0]})}
function stateRun(){var ctl=new AbortController(),timer=setTimeout(function(){ctl.abort()},6000);return fetch(API+'?client_key='+encodeURIComponent(KEY),{headers:{Accept:'application/json'},mode:'cors',cache:'no-store',signal:ctl.signal}).then(function(r){return r.text().then(function(t){var j;try{j=JSON.parse(t)}catch(e){throw Error('状态服务 HTTP '+r.status+' 返回非JSON')}if(!r.ok||j.error)throw Error(j.error||('状态服务 HTTP '+r.status));if(!j.data)throw Error('状态服务没有返回 data');return j.data})}).catch(function(e){if(e.name==='AbortError')throw Error('状态服务请求超过6秒未返回');throw e}).finally(function(){clearTimeout(timer)})}
function rest(table){if(!s.run||!s.run.id)return Promise.reject(Error('没有 Sandbox run_id'));return getJSON(SUPA+'/rest/v1/'+table+'?run_id=eq.'+encodeURIComponent(s.run.id)+'&order=created_at.desc',6000)}
function run(){return s.run||{agent_progress:0,risk_progress:0,backtest_progress:0,memory_count:0,run_count:0,state:{}}}
function state(){return run().state||{}}
function overview(){var r=run();return page('商业博弈总览','结果来自 Supabase 数据库 · '+(state().data_source||'Sandbox'),'<div class="grid">'+[['Agent进度',(r.agent_progress||0)+'%','数据库'],['策略回测',(r.backtest_progress==null?0:r.backtest_progress)+'%','数据库'],['风险控制',(r.risk_progress||0)+'%','数据库'],['学习记忆',r.memory_count||0,'条'],['运行次数',r.run_count||0,'次']].map(function(x){return'<div class="card"><div class="label">'+x[0]+'</div><div class="metric">'+x[1]+'</div><div class="label">'+x[2]+'</div></div>'}).join('')+'</div>')}
function market(){var d=state().market||{};return page('Web 市场情报','数据库结果 · '+(state().data_source||'Sandbox'),table(['观察','类型','强度','说明'],(d.signals||[]).map(function(x){return[x.name,x.type,x.strength,x.detail]})))}
function game(){var g=state().game||{};return page('商业博弈','数据库结果 · '+(state().data_source||'Sandbox'),table(['变量','数值'],[['我方产品',g.our_product],['对手',g.competitor],['场景',g.market],['竞品价格','¥'+g.competitor_price],['我方价格','¥'+g.our_price],['CPC','¥'+g.cpc],['CVR',(g.cvr||0)+'%']]))}
function ads(){var a=s.db.ads||{};return page('广告 / 流量','数据库结果 · 独立模块',table(['投放计划','状态','商品','场景','日预算','出价策略'],(a.plans||[]).map(function(x){return[x.name,x.status,x.product,x.scene,'¥'+x.daily_budget,x.bid_strategy]}))+table(['广告单元','商品','状态','关键词数','人群数','创意数'],(a.units||[]).map(function(x){return[x.name,x.product,x.status,x.keyword_count,x.audience_count,x.creative_count]}))+table(['关键词','类型','匹配','出价','展现','点击','CTR','CPC','成交','CVR','消耗','GMV','ROI','趋势'],(a.keywords||[]).map(function(x){return[x.keyword,x.keyword_type,x.match_type,'¥'+x.bid,x.impressions,x.clicks,x.ctr+'%',x.cpc,x.conversions,x.cvr+'%',x.spend,x.gmv,x.roi,x.trend]}))+table(['迁移类型','原关键词/场景','新关键词/场景','点击','成交','CVR','ROI','Agent结论','状态'],(a.moves||[]).map(function(x){return[x.move_type,x.source_keyword+' / '+x.source_scene,x.related_keyword+' / '+x.related_scene,x.clicks,x.conversions,x.cvr+'%',x.roi,x.agent_conclusion,x.status]}))+table(['人群','类型','行为','窗口','规模','覆盖','CVR','ROI','出价','溢价','重合'],(a.audiences||[]).map(function(x){return[x.name,x.audience_type,x.behavior,x.window_days+'天',x.size,x.coverage+'%',x.cvr+'%',x.roi,x.bid,x.premium+'%',x.overlap+'%']}))+table(['人群组合','规模','重合','CVR','ROI','Agent结论'],(a.combos||[]).map(function(x){return[x.name,x.size,x.overlap+'%',x.cvr+'%',x.roi,x.agent_conclusion]}))+table(['创意','类型','标题','审核','展现','点击','CTR','成交','ROI','状态'],(a.creatives||[]).map(function(x){return[x.name,x.creative_type,x.title,x.audit_status,x.impressions,x.clicks,x.ctr+'%',x.conversions,x.roi,x.status]}))+table(['渠道','资源位','展现','点击','CTR','消耗','成交','CVR','GMV','ROI'],(a.placements||[]).map(function(x){return[x.channel,x.placement,x.impressions,x.clicks,x.ctr+'%',x.spend,x.conversions,x.cvr+'%',x.gmv,x.roi]}))+table(['地域','展现','点击','CTR','消耗','成交','CVR','ROI'],(a.regions||[]).map(function(x){return[x.region,x.impressions,x.clicks,x.ctr+'%',x.spend,x.conversions,x.cvr+'%',x.roi]}))+table(['时段','星期','展现','点击','CTR','CPC','成交','CVR','ROI'],(a.timeslots||[]).map(function(x){return[x.slot,x.weekday,x.impressions,x.clicks,x.ctr+'%',x.cpc,x.conversions,x.cvr+'%',x.roi]}))+table(['否定/屏蔽词','点击','消耗','成交','Agent结论','状态'],(a.negative||[]).map(function(x){return[x.keyword,x.clicks,x.spend,x.conversions,x.agent_conclusion,x.status]}))+table(['Agent动作','目标','原因','结果','状态'],(a.actions||[]).map(function(x){return[x.action_type,x.target,x.reason,x.result,x.status]}))}
function experiments(){var e=state().experiments||{};return page('实验与回测','数据库测试结果 · '+(e.scenarios||[]).length+'个场景',table(['场景','轮数','ROI','风险','动作'],(e.scenarios||[]).map(function(x){return[x.name,x.rounds,x.roi,x.risk,x.action]})))}
function risk(){var r=run();return page('风险控制器','数据库状态',table(['指标','结果'],[['风险进度',(r.risk_progress||0)+'%'],['策略回测',(r.backtest_progress||0)+'%'],['运行次数',r.run_count||0]]))}
function jobs(){var r=run();return page('任务监控','数据库状态',table(['任务','状态','进度'],[['AGENT-20260929-005',r.agent_progress>=100?'已完成':r.agent_progress?'运行中':'就绪',(r.agent_progress||0)+'%'],['BT-20260929-004',r.backtest_progress>=100?'已完成':'运行中',(r.backtest_progress||0)+'%'],['RISK-20260929-006',r.risk_progress>=100?'已完成':r.risk_progress?'运行中':'等待 Agent',(r.risk_progress||0)+'%']]))}
function memory(){var m=state().memory||[];return page('学习记忆','数据库结果',table(['类型','内容','置信度','状态'],m.map(function(x){return[x.type,x.content,x.confidence,x.status]})))}
var views={overview:overview,market:market,game:game,ads:ads,experiments:experiments,risk:risk,jobs:jobs,memory:memory};
function render(){nav.forEach(function(b){b.classList.toggle('active',b.dataset.view===s.view)});if(s.loading&&!s.run){app.innerHTML='<h1 class="page-title">商业博弈总览</h1><div class="subtitle">正在读取数据库（最多等待6秒）…</div>';return}if(s.error&&!s.run){app.innerHTML='<h1 class="page-title">数据库连接失败</h1><div class="subtitle">'+esc(s.error)+'</div><div class="card"><b>网页已运行，但数据库没有成功返回结果。</b></div>';return}app.innerHTML=(views[s.view]||overview)()}
async function loadAds(){if(!s.run)return;var names=['sandbox_ad_plans','sandbox_ad_units','sandbox_ad_keywords','sandbox_ad_keyword_moves','sandbox_ad_audiences','sandbox_ad_audience_combos','sandbox_ad_creatives','sandbox_ad_placements','sandbox_ad_regions','sandbox_ad_timeslots','sandbox_ad_negative_keywords','sandbox_ad_agent_actions'];var v=await Promise.all(names.map(rest));s.db.ads={plans:v[0],units:v[1],keywords:v[2],moves:v[3],audiences:v[4],combos:v[5],creatives:v[6],placements:v[7],regions:v[8],timeslots:v[9],negative:v[10],actions:v[11]}}
async function load(silent){if(!silent){s.loading=true;s.error=null;render()}try{s.run=await directRun();try{var persisted=await stateRun();if(persisted&&persisted.id===s.run.id)s.run=Object.assign(s.run,persisted)}catch(e){console.warn('STATE_LAYER_OPTIONAL:',e.message)}try{await loadAds()}catch(e){console.warn('ADS_DB_PARTIAL:',e.message);s.db.ads={}}s.error=null}catch(e){if(!s.run){s.error=e.message;console.error('DATABASE_CONNECT_ERROR',e)}}finally{s.loading=false;render()}}
function go(view){if(!views[view])return;s.view=view;location.hash=view;render()}
nav.forEach(function(b){b.addEventListener('click',function(ev){ev.preventDefault();ev.stopPropagation();go(b.dataset.view)})});addEventListener('hashchange',function(){s.view=location.hash.slice(1)||'overview';render()});render();load();setInterval(function(){if(!document.hidden)load(true)},5000);
})();
