(function () {
  'use strict';
  var app=document.getElementById('app'),nav=Array.prototype.slice.call(document.querySelectorAll('.nav')),state={view:location.hash?location.hash.slice(1):'overview',runs:0};
  var scenarioNames=['正常市场','竞争加剧','流量成本上升','转化率下降','价格战','库存偏低','现金紧张','需求激增'];
  var memoryTypes={DECISION:'决策记录',COUNTER_EVIDENCE:'反证记录',STOP_SIGNAL:'停止信号',BREAKTHROUGH:'突破口发现',OPPONENT:'对手行为假设'};
  function esc(v){return String(v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function page(t,s,b){return '<h1 class="page-title">'+esc(t)+'</h1><div class="subtitle">'+esc(s)+'</div>'+b;}
  function cards(a){return '<div class="grid">'+a.map(function(x){return '<div class="card"><div class="label">'+esc(x[0])+'</div><div class="metric">'+esc(x[1])+'</div><div class="label">'+esc(x[2]||'')+'</div></div>';}).join('')+'</div>';}
  function table(h,rows){return '<div class="card"><table class="table"><thead><tr>'+h.map(function(x){return '<th>'+esc(x)+'</th>';}).join('')+'</tr></thead><tbody>'+rows.map(function(r){return '<tr>'+r.map(function(c){return '<td>'+c+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table></div>';}
  function renderOverview(){return page('商业博弈总览','Sandbox 模拟数据 · 当前系统状态',cards([['市场状态','混合市场','置信度 0.62'],['今日广告消耗','¥1,284','预算 ¥2,000'],['当前 ROI','3.18','目标 ≥ 2.60'],['可执行策略','7','3 个需审批']]))}
  function renderMarket(){return page('Web 市场情报','Sandbox 外部市场信号，不代表真实平台抓取',table(['观察','状态','强度','证据'],[['竞争对手降价','价格压力','高','竞品可见价格较昨日下降约6%'],['流量成本上升','流量成本压力','中高','同类广告 CPC 连续3个窗口上升'],['需求变化','需求变化','中','搜索/内容热度上升，尚未完成归因'],['平台规则','平台信号','待验证','等待官方来源确认']]))}
  function renderGame(){return page('商业博弈','输入我、对手、市场，运行多轮 Sandbox Agent',cards([['竞品价格','¥83.70','-6.1%'],['平均 CPC','¥2.14','+14.2%'],['类目 CVR','4.8%','-8.3%'],['库存覆盖','18 天','安全'],['现金可用','¥42,600','安全']])+'<div class="card"><button class="action" data-action="run-agent"><b>运行模拟 Agent</b><br><span class="muted">多轮博弈 → 对手响应 → 突破口</span></button><div id="agentOutput" class="notice">等待运行。</div></div>')}
  function renderAds(){var groups=[['核心成交人群','近30天购买用户','8.4万','转化率 6.8%','¥1.32'],['高意向人群','加购未购买','3.1万','转化率 4.9%','¥1.86'],['潜在人群','类目兴趣/搜索行为','26.8万','转化率 2.7%','¥2.31'],['老客复购','近90天购买用户','5.7万','转化率 8.2%','¥1.08']];var kws=[['酸面包 早餐','精准','¥2.18','4.9%','3.42','高意向'],['全麦面包','词组','¥1.86','3.8%','2.91','稳定'],['低糖面包','词组','¥2.03','3.5%','2.64','可扩量'],['面包推荐','广泛','¥2.76','2.1%','1.74','降价观察'],['早餐面包','广泛','¥2.41','2.6%','2.08','测试中'],['酸面包怎么吃','内容词','¥1.37','3.9%','2.88','内容机会']];var plans=[['计划A · 核心成交','搜索广告','¥620','2.9','3.42','正常'],['计划B · 高意向','搜索+人群','¥360','2.4','2.91','加量候选'],['计划C · 潜在人群','兴趣/重定向','¥184','1.8','2.17','观察'],['计划D · 内容引流','内容投放','¥120','1.5','1.86','风险']];return page('广告 / 流量','完整查看：计划 → 人群 → 关键词 → 出价 → 点击 → 转化 → ROI',cards([['今日消耗','¥1,284','预算 ¥2,000'],['曝光','186.4万','+12.8%'],['点击','5.79万','CTR 3.11%'],['成交','2,784','CVR 4.81%'],['平均 CPC','¥2.14','竞价压力 +14.2%'],['边际 ROI','1.86','进入观察区']])+'<div class="card"><h3 class="section-title">① 投放计划</h3>'+table(['计划','渠道','今日消耗','CPC','ROI','状态'],plans.map(function(r){return r.map(esc);}))+'</div><div class="card" style="margin-top:12px"><h3 class="section-title">② 人群</h3>'+table(['人群','来源/定义','规模','转化率','平均 CPC'],groups.map(function(r){return r.map(esc);}))+'</div><div class="card" style="margin-top:12px"><h3 class="section-title">③ 关键词 / 搜索词</h3>'+table(['关键词','匹配方式','出价','点击率','ROI','判断'],kws.map(function(r){return [esc(r[0]),esc(r[1]),esc(r[2]),esc(r[3]),esc(r[4]),'<span class="tag">'+esc(r[5])+'</span>'];}))+'</div><div class="grid2" style="margin-top:12px"><div class="card"><h3 class="section-title">④ 出价与预算动作</h3><button class="action" data-action="run-agent">核心成交人群：模拟 +10% 预算</button><button class="action" data-action="run-agent">高意向人群：模拟提高出价 8%</button><button class="action" data-action="run-agent">低 ROI 关键词：模拟降价 12%</button><button class="action" data-action="run-agent">潜在人群：模拟扩大 20%</button></div><div class="card"><h3 class="section-title">⑤ Agent 判断</h3><div class="event"><b>可扩量：核心成交人群</b><small>ROI 3.42，边际空间仍存在</small></div><div class="event"><b>谨慎：高意向人群</b><small>竞争上升，先小额验证</small></div><div class="event"><b>收缩：面包推荐</b><small>边际 ROI 1.74，进入风险区</small></div></div></div>');}
  function renderExperiments(){var rows=scenarioNames.map(function(s,i){return ['<b>'+s+'</b>','30','¥'+(900+i*117),[3.42,2.91,2.31,1.88,2.16,2.74,2.03,3.86][i].toFixed(2),i%3===0?'高':'中','<span class="tag">'+(i%2?'切换策略':'继续观察')+'</span>'];});return page('实验与回测','8 个场景 × 30 轮 · Sandbox 压力测试',cards([['场景','8','全部已生成'],['轮次','240','8 × 30'],['风险拦截','17','模拟统计'],['学习信号','128','模拟统计']])+table(['场景','轮数','投入','最终 ROI','风险','策略状态'],rows)+'<div class="card"><button class="primary" data-action="rerun">重新运行全部模拟</button><div id="runStatus" class="notice">尚未重新运行。</div></div>')}
  function renderRisk(){return page('07 · 风险控制器','统一执行前 + 执行后风险状态机',cards([['综合风险','中等','当前模拟'],['资金风险','0.18','低'],['单位经济','0.42','边际 ROI 下降'],['市场风险','0.58','拥挤/竞价'],['经营风险','0.08','库存安全'],['对手风险','0.61','反击可能']]))}
  function renderJobs(){return page('任务监控','模拟 Agent / Web 扫描 / 回测任务状态',table(['任务','状态','进度','类型'],[['WEB-20260929-001','运行中','72%','Web 市场扫描'],['BT-20260929-004','已完成','100%','30×8 回测'],['AGENT-20260929-005','就绪','0%','商业博弈 Agent'],['RISK-20260929-006','就绪','0%','风险控制器']]))}
  function renderMemory(){var rows=[['DECISION','降低低毛利计划预算','0.82','有效'],['COUNTER_EVIDENCE','正常情况下，竞品降价会分流我方转化；但本轮实验中，竞品降价后我方转化率仅从 4.8% 降至 4.7%，未出现预期幅度的下降。反证不是“竞品降价没有影响”，而是：当我方商品在品牌/评价/内容种草/差异化卖点/高意向人群中形成较强偏好，且竞品降价主要吸引价格敏感用户时，价格冲击可能被人群结构差异、信任优势和非价格价值部分抵消。需要继续验证：①我方老客占比是否较高；②用户是否存在明显的品牌/评价偏好；③竞品降价是否只覆盖部分关键词/人群；④我方核心关键词排名与内容触达是否保持；⑤竞品降价后我方点击率是否下降但 CVR 保持。','0.86','有效'],['STOP_SIGNAL','边际 ROI 持续下降','0.91','有效'],['BREAKTHROUGH','转换到内容/产品差异化','0.65','测试中'],['OPPONENT','竞品可能跟随内容打法','0.58','假设中']].map(function(r){return ['<b>'+esc(memoryTypes[r[0]])+'</b>',esc(r[1]),esc(r[2]),'<span class="tag">'+esc(r[3])+'</span>'];});return page('学习记忆','Agent 从每一轮结果中保存的模拟学习信号',table(['类型','内容','置信度','状态'],rows)+'<div class="card"><h3 class="section-title">反证记录的判断规则</h3><div class="notice"><b>先承认基准规律：</b>竞品降价通常会产生负面价格冲击。<br><b>再寻找偏离条件：</b>我方转化没有按预期下降时，不把它记录成“竞品降价无效”，而是记录“哪些条件抵消了价格冲击”。<br><b>最后进入下一轮实验：</b>逐项关闭品牌、评价、内容、人群、关键词覆盖等因素，寻找真正的因果条件。</div></div>')}
  function renderBreakthrough(){return page('突破口','Agent 根据失败信号自动切换突破路径',cards([['当前突破口','转化 / 内容','Sandbox 置信度 0.65'],['博弈鲁棒性','0.71','对手反击后仍可继续'],['对手威胁','3 类','价格 / 流量 / 内容']]))}
  function renderInputs(){return page('博弈输入','把“我、对手、市场”拆开输入，再交给 Agent','<div class="card"><h3 class="section-title">我方 / 对手 / 市场</h3><div class="notice">商品售价 ¥89 · 毛利率 32% · 库存 18 天 · 可用现金 ¥42,600 · 竞品 ¥83.70 · 平均 CPC ¥2.14 · 类目需求 +11%</div><button class="primary" data-action="run-agent">运行模拟 Agent</button><div id="inputAgentOutput" class="notice">等待运行。</div></div>')}
  var renders={overview:renderOverview,market:renderMarket,game:renderGame,ads:renderAds,experiments:renderExperiments,risk:renderRisk,jobs:renderJobs,memory:renderMemory,breakthrough:renderBreakthrough,inputs:renderInputs};
  function runAgent(){state.runs++;var out='第 '+state.runs+' 次模拟 Agent 已完成：发现【边际 ROI 下降】→ 检查人群与关键词 → 模拟对手反应 → 风险复核 → 建议收缩低 ROI 关键词，把预算转向高意向人群。<br><br><b>下一步：</b>小额验证 · <b>停止条件：</b>边际 ROI &lt; 0.8';['agentOutput','inputAgentOutput'].forEach(function(id){var e=document.getElementById(id);if(e)e.innerHTML=out;});}
  function render(){var fn=renders[state.view]||renders.overview;app.innerHTML=fn();nav.forEach(function(b){b.classList.toggle('active',b.getAttribute('data-view')===state.view);});window.scrollTo(0,0);}
  nav.forEach(function(btn){btn.addEventListener('click',function(e){e.preventDefault();state.view=btn.getAttribute('data-view');location.hash=state.view;render();});});
  document.addEventListener('click',function(e){var a=e.target.closest('[data-action]');if(!a)return;var action=a.getAttribute('data-action');if(action==='run-agent')runAgent();if(action==='rerun'){var s=document.getElementById('runStatus');if(s)s.innerHTML='已刷新：Sandbox 数据重新计算完成。时间：'+new Date().toLocaleTimeString();}});
  window.addEventListener('hashchange',function(){state.view=location.hash.slice(1)||'overview';render();});window.runSandboxAgent=runAgent;window.runSandboxBenchmark=function(){state.view='experiments';location.hash='experiments';render();};render();
})();
