(function(){'use strict';
var STATE_API='https://skuoxmrzlxhebzhfgbyn.supabase.co/functions/v1/sandbox-state';
var app=document.getElementById('app'),nav=[].slice.call(document.querySelectorAll('.nav')),state={view:location.hash?location.hash.slice(1):'overview',run:null};
var clientKey=localStorage.getItem('sandbox_client_key');if(!clientKey){clientKey='web-'+crypto.randomUUID();localStorage.setItem('sandbox_client_key',clientKey)}
var scenarioNames=['正常市场','竞争加剧','流量成本上升','转化率下降','价格战','库存偏低','现金紧张','需求激增'];var memoryTypes={DECISION:'决策记录',COUNTER_EVIDENCE:'反证记录',STOP_SIGNAL:'停止信号',BREAKTHROUGH:'突破口发现',OPPONENT:'对手行为假设'};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function pct(v){return Math.max(0,Math.min(100,Number(v)||0))}
function api(method,body){return fetch(STATE_API,{method:method||'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}).then(function(r){if(!r.ok)throw new Error('状态服务 '+r.status);return r.json()})}
function load(){return fetch(STATE_API+'?client_key='+encodeURIComponent(clientKey)).then(function(r){return r.json()}).then(function(x){if(x.data)state.run=x.data;else return api('POST',{op:'create',client_key:clientKey}).then(function(y){state.run=y.data})}).then(render).catch(function(e){console.warn(e);render()})}
function save(patch,event){if(!state.run)return Promise.resolve();Object.assign(state.run,patch);return api('POST',{op:'update',id:state.run.id,patch:patch,event:event||null}).then(function(x){if(x.data)state.run=x.data}).catch(function(e){console.warn(e)})}
function page(t,s,b){return'<h1 class="page-title">'+esc(t)+'</h1><div class="subtitle">'+esc(s)+'</div>'+b}function cards(a){return'<div class="grid">'+a.map(function(x){return'<div class="card"><div class="label">'+esc(x[0])+'</div><div class="metric">'+esc(x[1])+'</div><div class="label">'+esc(x[2]||'')+'</div></div>'}).join('')+'</div>'}function table(h,rows){return'<div class="card"><table class="table"><thead><tr>'+h.map(function(x){return'<th>'+esc(x)+'</th>'}).join('')+'</tr></thead><tbody>'+rows.map(function(r){return'<tr>'+r.map(function(x){return'<td>'+x+'</td>'}).join('')}</tr>'}).join('')}</tbody></table></div>'}
function renderOverview(){var r=state.run||{};return page('商业博弈总览','Sandbox 模拟数据 · 数据已持久化到 Supabase',cards([['市场状态','混合市场','置信度 0.62'],['Agent进度',pct(r.agent_progress)+'%','刷新后保留'],['风险控制',pct(r.risk_progress)+'%','刷新后保留'],['运行次数',r.run_count||0,'持续累计']])+'<div class="card"><h3 class="section-title">持久化状态</h3><div class="notice">任务状态、运行次数、回测进度、Risk Controller 进度和事件记录不再只存在浏览器内存。刷新网页后会重新读取。</div></div>')}
function renderMarket(){return page('Web 市场情报','Sandbox 外部市场信号',table(['观察','状态','强度','证据'],[['竞争对手降价','价格压力','高','竞品可见价格下降约6%'],['流量成本上升','流量成本压力','中高','同类广告 CPC 连续3个窗口上升'],['需求变化','需求变化','中','搜索/内容热度上升'],['平台规则','平台信号','待验证','等待官方来源确认']]))}
function renderGame(){var r=state.run||{};return page('商业博弈','我方、对手、市场的多轮模拟',cards([['竞品价格','¥83.70','-6.1%'],['平均 CPC','¥2.14','+14.2%'],['类目 CVR','4.8%','-8.3%'],['库存覆盖','18 天','安全']])+'<div class="card"><button class="primary" data-action="run-agent">运行模拟 Agent</button><div class="notice">运行状态：'+esc(r.status||'就绪')+' · Agent '+pct(r.agent_progress)+'%</div></div>')}
function renderAds(){return page('广告 / 流量','模拟广告计划、人群、关键词与边际 ROI',cards([['今日消耗','¥1,284','预算 ¥2,000'],['平均 CPC','¥2.14','竞价压力 +14.2%'],['CTR','3.1%','Sandbox'],['边际 ROI','1.86','观察区']])+table(['投放计划','人群','关键词','消耗','ROI'],[['核心成交','近30天购买 / 高意向','酸面包早餐','¥486','4.12'],['高意向','加购未购买','早餐酸面包','¥318','3.64'],['潜在人群','类目兴趣 / 搜索行为','健康早餐面包','¥264','2.38'],['内容引流','内容互动人群','下午茶面包','¥216','2.71']])+'<div class="card"><h3 class="section-title">关键词迁移实验</h3><div class="notice"><b>同场景相关关键词：</b>早餐酸面包 → 全麦早餐面包 → 健康早餐面包<br><b>跨场景关键词：</b>早餐 → 下午茶 → 办公室加餐 → 咖啡搭配</div></div>')}
function renderExperiments(){var rows=scenarioNames.map(function(s,i){return['<b>'+s+'</b>','30','¥'+(900+i*117),[3.42,2.91,2.31,1.88,2.16,2.74,2.03,3.86][i].toFixed(2),i%3===0?'高':'中',i%2?'切换策略':'继续观察']});var r=state.run||{};return page('实验与回测','8 个场景 × 30 轮 · Sandbox 压力测试',cards([['场景','8','全部已生成'],['轮次','240','8 × 30'],['风险拦截','17','模拟统计'],['学习信号','128','模拟统计']])+table(['场景','轮数','投入','最终 ROI','风险','策略状态'],rows)+'<div class="card"><button class="primary" data-action="start-chain">启动 / 继续完整模拟链</button><div id="chainStatus" class="notice">Agent '+pct(r.agent_progress)+'% · Risk '+pct(r.risk_progress)+'%</div></div>')}
function renderRisk(){var r=state.run||{};return page('07 · 风险控制器','统一执行前 + 执行后风险状态机',cards([['综合风险','中等','当前模拟'],['Agent进度',pct(r.agent_progress)+'%','风险链已接入'],['风险控制进度',pct(r.risk_progress)+'%','刷新后保留'],['学习记忆',r.memory_count||0,'已记录信号']])+'<div class="card"><div class="event"><b>执行前：允许 / 有条件允许 / 拦截</b><small>先决定能不能做、能做多少</small></div><div class="event"><b>执行后：边际 ROI / 现金 / 库存 / 市场停止信号</b><small>结果写入学习记忆</small></div></div>')}
function renderJobs(){var r=state.run||{};var rows=[['AGENT-20260929-005',r.agent_progress>=100?'已完成':r.agent_progress?'运行中':'就绪',r.agent_progress,'商业博弈 Agent'],['BT-20260929-004','已完成',100,'策略回测'],['RISK-20260929-006',r.risk_progress>=100?'已完成':r.risk_progress?'运行中':r.agent_progress?'等待结果':'就绪',r.risk_progress,'风险控制器']];return page('任务监控','完整模拟链：Agent → 回测 → 风险控制 → 学习记忆',table(['任务','状态','进度','类型'],rows.map(function(x){return[x[0],x[1],'<b>'+x[2]+'%</b>',x[3]]}))+'<div class="card"><button class="primary" data-action="start-chain">启动 / 继续完整模拟链</button><div id="runStatus" class="notice">数据库持久化已启用。刷新不会把进度恢复到0%。</div></div>')}
function renderMemory(){var rows=[['DECISION','降低低毛利计划预算','0.82','有效'],['COUNTER_EVIDENCE','竞品降价后我方转化下降幅度低于模型预期；继续寻找老客占比、品牌信任、内容价值、关键词覆盖、人群重叠度等抵消条件','0.67','测试中'],['STOP_SIGNAL','边际 ROI 持续下降','0.91','有效'],['BREAKTHROUGH','转换到内容/产品差异化','0.65','测试中'],['OPPONENT','竞品可能跟随内容打法','0.58','假设中']].map(function(r){return['<b>'+esc(memoryTypes[r[0]])+'</b>',esc(r[1]),r[2],'<span class="tag">'+r[3]+'</span>']});return page('学习记忆','Agent 每轮模拟形成的学习信号',table(['类型','内容','置信度','状态'],rows))}
var renders={overview:renderOverview,market:renderMarket,game:renderGame,ads:renderAds,experiments:renderExperiments,risk:renderRisk,jobs:renderJobs,memory:renderMemory};
function runAgent(){var r=state.run;if(!r)return;var p=pct(r.agent_progress)+25,rp=Math.max(pct(r.risk_progress),Math.max(0,p-10));save({status:p>=100?'completed':'running',agent_progress:p,risk_progress:rp,run_count:(r.run_count||0)+1,memory_count:(r.memory_count||0)+(p>=50?1:0),state:Object.assign({},r.state||{},{last_action:'运行模拟 Agent',last_result:'边际ROI下降 → 寻找抵消条件'})},{type:'agent',title:'模拟 Agent 推进一步',detail:'Agent 与 Risk Controller 进度已保存'}).then(render)}
function startChain(){var r=state.run;if(!r)return;var p=pct(r.agent_progress)+20,rp=Math.max(pct(r.risk_progress),Math.max(0,p-5));save({status:p>=100?'completed':'running',agent_progress:p,backtest_progress:100,risk_progress:rp,run_count:(r.run_count||0)+1,memory_count:(r.memory_count||0)+1,state:Object.assign({},r.state||{},{chain:['Agent','策略回测','Risk Controller','学习记忆'],last_action:'推进完整模拟链'})},{type:'chain',title:'完整模拟链推进',detail:'Agent → 回测 → 风险控制 → 学习记忆'}).then(render)}
function render(){app.innerHTML=(renders[state.view]||renderOverview)();nav.forEach(function(b){b.classList.toggle('active',b.getAttribute('data-view')===state.view)});window.scrollTo(0,0)}nav.forEach(function(b){b.addEventListener('click',function(e){e.preventDefault();state.view=b.getAttribute('data-view');location.hash=state.view;render()})});document.addEventListener('click',function(e){var a=e.target.closest('[data-action]');if(!a)return;if(a.getAttribute('data-action')==='run-agent')runAgent();if(a.getAttribute('data-action')==='start-chain')startChain()});window.addEventListener('hashchange',function(){state.view=location.hash.slice(1)||'overview';render()});render();load();
})();
