(function(){
  'use strict';
  var app=document.getElementById('app');
  var navs=document.querySelectorAll('.nav');
  var BASE='https://skuoxmrzlxhebzhfgbyn.supabase.co';
  var KEY='sb_publishable_u46tZ4GMUgwqSYhMJNFG8Q_IzYwl95T';
  var CLIENT='ecommerce-agent-sandbox-v1';
  var state={run:null,game:[],market:[],backtests:[],events:[],memories:[],risk:[],tasks:[],rounds:[],ads:{}};
  var adTables=['sandbox_ad_plans','sandbox_ad_units','sandbox_ad_keywords','sandbox_ad_keyword_moves','sandbox_ad_audiences','sandbox_ad_audience_combos','sandbox_ad_creatives','sandbox_ad_placements','sandbox_ad_regions','sandbox_ad_timeslots','sandbox_ad_negative_keywords','sandbox_ad_agent_actions','sandbox_ad_results','sandbox_ad_reports'];
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function zh(v){var m={'HOLD':'保持观察','CHANGE_KEYWORD':'调整关键词','CHANGE_TARGETING':'调整定向','CHANGE_CONTENT':'调整内容','CHANGE_AUDIENCE':'调整人群','CHANGE_CREATIVE':'调整创意','CHANGE_PRICE':'调整价格','INCREASE_BUDGET':'增加预算','DECREASE_BUDGET':'降低预算','INCREASE_BID':'提高出价','DECREASE_BID':'降低出价','DEFEND_TRAFFIC':'防守流量','SHIFT_CONTENT':'切换内容','VALUE_ATTACK':'价值竞争','NO_CLEAR_GAP':'暂未发现明确突破口','ALLOW':'通过','BLOCK':'拦截','STOP':'停止','CONTINUE':'继续'};return m[v]||v||'未知';}
  function show(title,sub,body){app.innerHTML='<h1 class="page-title">'+esc(title)+' <span style="font-size:16px;font-weight:500;color:var(--accent);margin-left:10px">我变 → 对手学 → 我再变</span></h1><div class="subtitle">'+esc(sub)+'</div>'+body;}
  function card(title,value){return '<div class="card"><div class="label">'+esc(title)+'</div><div class="metric">'+esc(value)+'</div></div>';}
  function notice(t){return '<div class="card"><div class="notice">'+esc(t)+'</div></div>';}
  function table(headers,rows){var h='<div class="card"><table class="table"><thead><tr>';headers.forEach(function(x){h+='<th>'+esc(x)+'</th>';});h+='</tr></thead><tbody>';if(!rows.length)return h+'</tbody></table><div class="notice">暂无记录</div></div>';rows.slice(0,100).forEach(function(r){h+='<tr>';headers.forEach(function(_,i){h+='<td>'+esc(r[i])+'</td>';});h+='</tr>';});return h+'</tbody></table></div>';}
  function get(url){return fetch(url,{headers:{apikey:KEY,Authorization:'Bearer '+KEY,Accept:'application/json'},cache:'no-store'}).then(function(r){return r.text().then(function(t){var d;try{d=JSON.parse(t);}catch(e){throw Error('数据接口返回异常 HTTP '+r.status);}if(!r.ok)throw Error('数据接口 HTTP '+r.status);return d;});});}
  function url(name,scoped){var q='?select=*&order=id.desc';if(scoped&&state.run&&state.run.id)q+='&run_id=eq.'+encodeURIComponent(state.run.id);return BASE+'/rest/v1/'+name+q;}
  function load(){return get(BASE+'/rest/v1/sandbox_runs?select=id,status,updated_at,client_key,agent_progress,backtest_progress,risk_progress,memory_count,run_count,state&client_key=eq.'+encodeURIComponent(CLIENT)+'&order=updated_at.desc&limit=1').then(function(r){state.run=r[0]||null;return Promise.all([get(url('sandbox_game_states',true)),get(url('sandbox_market_signals',true)),get(url('sandbox_backtests',true)),get(url('sandbox_events',true)),get(url('sandbox_memories',true)),get(url('sandbox_risk_results',true)),get(url('sandbox_task_results',true)),get(url('sandbox_agent_rounds',true))]);}).then(function(x){state.game=x[0]||[];state.market=x[1]||[];state.backtests=x[2]||[];state.events=x[3]||[];state.memories=x[4]||[];state.risk=x[5]||[];state.tasks=x[6]||[];state.rounds=x[7]||[];return Promise.all(adTables.map(function(n){return get(url(n)).then(function(r){state.ads[n]=r||[];});}));});}
  function overview(){show('商业博弈总览','稳定运行内核 · 独立页面启动层','<div class="grid">'+card('Sandbox Run',state.run?state.run.status:'未连接')+card('商业博弈记录',state.game.length)+card('市场信号',state.market.length)+card('Agent轮次',state.rounds.length)+'</div><div class="card"><b>连续博弈</b><div style="font-size:18px;margin-top:6px">我变 → 对手学 → 我再变</div><div class="muted">页面模块已经与主启动链隔离；单个模块异常不会阻塞导航。</div></div>');}
  function market(){show('外部市场情报','Sandbox 市场信号',table(['名称','类型','强度','说明'],state.market.map(function(x){return[x.name,x.signal_type,x.strength,x.detail];})));}
  function logic(){var list=window.EA_GAME_LOGICS||[];var h='<div class="card"><div class="label">50套博弈逻辑</div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:8px">';list.forEach(function(x){h+='<button class="module-choice" data-logic="'+esc(x.id)+'"><b>'+esc(x.id)+' '+esc(x.name)+'</b><div class="muted">'+esc(x.type)+'</div></button>';});h+='</div></div><div id="logic-detail">'+(list[0]?detailLogic(list[0]):notice('博弈逻辑库正在加载；导航本身已可用。'))+'</div>';show('博弈逻辑','独立模块',h);document.querySelectorAll('[data-logic]').forEach(function(b){b.onclick=function(){var x=list.find(function(a){return a.id===b.dataset.logic;});if(x)document.getElementById('logic-detail').innerHTML=detailLogic(x);};});}
  function detailLogic(x){return '<div class="card"><h2>'+esc(x.name)+'</h2>'+((x.steps||[]).map(function(s,i){return'<div class="notice">第'+(i+1)+'步：'+esc(s)+'</div>';}).join(''))+'</div>';}
  function library(view,title){var map={'positive-attacks':'EA_POSITIVE_ATTACK_LIBRARY','threats':'EA_THREAT_LIBRARY','human-behavior':'EA_HUMAN_BEHAVIOR_LIBRARY'};var list=window[map[view]]||[];var h='<div class="card"><div class="label">当前可用条目：'+list.length+'</div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:8px">';list.forEach(function(x){h+='<div class="notice"><b>'+esc(x.id||'')+' '+esc(x.name||x.title||'')+'</b><br><span class="muted">'+esc(x.signal||x.style||x.category||x.description||'')+'</span></div>';});h+='</div></div>';show(title,'独立模块',h);}
  function strategy(){show('连续博弈策略中心','我变 → 对手学 → 我再变',agentRounds());}
  function agentRounds(){if(!state.rounds.length)return notice('暂无模拟轮次。');return table(['轮次','我方动作','实际对手响应','下一动作','风险'],state.rounds.map(function(x){return['R'+x.round,zh(x.action),zh(x.actual_opponent_response),zh(x.next_action_hint),x.risk_approved?'通过':'拦截';}));}
  function adGame(){var blocks=['① 投流博弈地图','② 正向投流','③ 逆向防守','④ 对手响应矩阵','⑤ 预算博弈','⑥ 投流陷阱','⑦ 连续投流','⑧ 投流攻防演变'];var h='<div class="grid">';blocks.forEach(function(x,i){h+='<div class="card"><h3>'+x+'</h3><div class="muted">独立模块 · 可逐步接入真实 Sandbox 数据</div><button class="module-action" data-ad="'+i+'">查看模块</button></div>';});h+='</div><div class="card"><b>进入连续博弈策略中心 →</b></div>';show('广告投流博弈','独立模块 · 当前先保证稳定运行',h);}
  function ads(){var h='<div class="grid">';adTables.forEach(function(n){h+=card(n.replace('sandbox_ad_',''),(state.ads[n]||[]).length);});h+='</div>';show('广告流量','Sandbox 广告数据',h);}
  function simple(title,rows,headers){show(title,'独立模块',table(headers,rows));}
  function render(view){navs.forEach(function(n){n.classList.toggle('active',n.dataset.view===view);});try{if(view==='overview')overview();else if(view==='market')market();else if(view==='game-logic')logic();else if(view==='positive-attacks')library(view,'正向攻击');else if(view==='threats')library(view,'对手攻击面');else if(view==='human-behavior')library(view,'人性行为演变');else if(view==='strategy-center')strategy();else if(view==='ad-bidding-game')adGame();else if(view==='ads')ads();else if(view==='experiments')simple('实验与回测',state.backtests.map(function(x){return[x.scenario,x.rounds,x.roi,x.risk,x.action,x.created_at];}),['场景','轮次','ROI','风险','动作','时间']);else if(view==='risk')simple('风险控制器',state.risk.map(function(x){return[x.metric,JSON.stringify(x.value),x.created_at];}),['指标','结果','时间']);else if(view==='jobs')simple('任务监控',state.tasks.map(function(x){return[x.task_type,x.status,(x.progress||0)+'%',x.created_at];}),['任务类型','状态','进度','时间']);else if(view==='memory')simple('学习记忆',state.memories.map(function(x){return[x.memory_type,x.content,x.confidence,x.status,x.created_at];}),['记忆类型','内容','置信度','状态','时间']);else simple('商业博弈',state.game.map(function(x){return[x.product,x.competitor,x.scenario,x.competitor_price,x.our_price,x.cpc,x.cvr];}),['产品','竞品','场景','竞品价格','我方价格','CPC','CVR']);}catch(e){show('模块加载失败','其他页面不受影响',notice(e.message));}}
  function bind(){navs.forEach(function(n){n.addEventListener('click',function(e){e.preventDefault();var v=n.getAttribute('data-view');location.hash=v;render(v);});});window.addEventListener('hashchange',function(){render(location.hash.slice(1)||'overview');});window.__EA_BOOT_SHELL__=true;render(location.hash.slice(1)||'overview');load().then(function(){render(location.hash.slice(1)||'overview');}).catch(function(e){show('页面已启动 · 数据连接失败','导航仍然可用',notice(e.message));});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();